version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zk
    ports:
      - 2181:2181 #zookeeper client port

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zk:2181